spring:

  # Database Settings
  datasource:
    url: jdbc:postgresql://localhost:5432/db_bank_account
    username: king
    password: 123456789
    initialization-mode: never
    initialize: false

  # Spring Data JPA Settings
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: false

# Properties
app:
  name: Microservice account Production
  description: Accounts Microservice manages client information and bank accounts, including account creation, transactions, and balance tracking with auditing and security features.
  build: 3.0.0
  support-emails: bank-contact9@support.com,bank-contact7@support.com,bank-contact8@support.com
  support-phones:
    - +1 34567690
    - +1 67654445
    - +1 77650085
