spring:

  # Database Settings
  datasource:
    url: jdbc:postgresql://account-db:5432/db_account
    username: king
    password: mE4NrGqVeWgT0tkZvugZVA==
    initialization-mode: always
    initialize: true

  # Spring Data JPA Settings
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

# Properties
app:
  name: Microservice account Dev
  description: Accounts Microservice manages client information and bank accounts, including account creation, transactions, and balance tracking with auditing and security features.
  build: 1.0.0
  support-emails: bank-contact1@support.com,bank-contact2@support.com,bank-contact3@support.com
  support-phones:
    - +33 34567690
    - +33 67654445
    - +33 77650085
