spring:

  # Database Settings
  datasource:
    url: jdbc:postgresql://card-db:5432/db_card
    username: king
    password: Lf6N7KV+ypznOEaeiIQWsQ==
    initialization-mode: never
    initialize: false

  # Spring Data JPA Settings
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: false

# Proprties
app:
  name: Microservice card Test
  description: Card Microservice manages client payment cards, including card issuance, activation, deactivation, and lifecycle management.
  build: 2.0.0
  cardNumber: 99TBA601
