spring:

  # Database Settings
  datasource:
    url: jdbc:postgresql://card-db:5432/db_card
    username: king
    password: Lf6N7KV+ypznOEaeiIQWsQ==
    initialization-mode: always
    initialize: true

  # Spring Data JPA Settings
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true


# Proprties
app:
  name: Microservice card Development
  description: Card Microservice manages client payment cards, including card issuance, activation, deactivation, and lifecycle management.
  build: 1.0.0
  cardNumber: FFFFF789
